### ISSUE TITLE
Sync did not happen. You're must select at least one site!

### ISSUE THREAD

**Issue by MrAntoine** [pablodiloreto/wpm-user-sync#13]
**Describe the bug**

Hello, 
When I select my websites I have this error message "Sync did not happen. You're must select at least one site!" I had 3 selectionned websites... 

Thank's in advance for your help

**Comment by soydiloreto** [comment]
Hello @MrAntoine ! This error was fixed in v1.3
Thank you for your report and sorry the delay!
